onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false
